# Form implementation generated from reading ui file 'StartUI.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(504, 503)
        MainWindow.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-image: url(\"background_grass.jpg\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}\n"
"")
        MainWindow.setWindowFilePath("")
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.algoCbBox = QtWidgets.QComboBox(parent=self.centralwidget)
        self.algoCbBox.setGeometry(QtCore.QRect(240, 80, 201, 31))
        self.algoCbBox.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.algoCbBox.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.algoCbBox.setStyleSheet("QComboBox::drop-down {\n"
"    border: none;\n"
"    image: url(\"arrow_basic_s.png\"); \n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n"
" QComboBox::drop-down:on {\n"
"    image: url(\"arrow_basic_s_small.png\");\n"
"    width: 10px;\n"
"    height: 10px;\n"
"}\n")
        self.algoCbBox.setEditable(False)
        self.algoCbBox.setMinimumContentsLength(1)
        self.algoCbBox.setIconSize(QtCore.QSize(10, 10))
        self.algoCbBox.setDuplicatesEnabled(False)
        self.algoCbBox.setFrame(True)
        self.algoCbBox.setObjectName("algoCbBox")
        self.algoCbBox.addItem("")
        self.algoCbBox.addItem("")
        self.algoCbBox.addItem("")
        self.algoCbBox.addItem("")
        self.algoCbBox.addItem("")
        self.algoCbBox.addItem("")
        self.selectLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.selectLabel.setGeometry(QtCore.QRect(50, 70, 181, 51))
        font = QtGui.QFont()
        font.setFamily("Book Antiqua")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.selectLabel.setFont(font)
        self.selectLabel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.selectLabel.setAutoFillBackground(False)
        self.selectLabel.setStyleSheet("QLabel {\n"
"    color: rgb(25, 76, 152);\n"
"}")
        self.selectLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.selectLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.selectLabel.setObjectName("selectLabel")
        self.imageLevelView = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.imageLevelView.setEnabled(True)
        self.imageLevelView.setGeometry(QtCore.QRect(40, 140, 281, 281))
        self.imageLevelView.setAutoFillBackground(False)
        self.imageLevelView.setStyleSheet("")
        self.imageLevelView.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.imageLevelView.setObjectName("imageLevelView")
        self.startButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.startButton.setGeometry(QtCore.QRect(360, 280, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.startButton.setFont(font)
        self.startButton.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.startButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.startButton.setStyleSheet("QPushButton {\n"
"    border-color: rgb(2, 143, 218);\n"
"    color: rgb(54, 132, 184);\n"
"    background-image: url(\"button_rectangle_depth_border.png\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}")
        self.startButton.setIconSize(QtCore.QSize(93, 28))
        self.startButton.setObjectName("startButton")
        self.exitButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.exitButton.setGeometry(QtCore.QRect(360, 350, 101, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.exitButton.setFont(font)
        self.exitButton.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.exitButton.setAutoFillBackground(False)
        self.exitButton.setStyleSheet("QPushButton {\n"
"    border-color: rgb(2, 143, 218);\n"
"    color: rgb(54, 132, 184);\n"
"    background-image: url(\"button_rectangle_depth_border.png\");\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"}")
        self.exitButton.setObjectName("exitButton")
        self.rightButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.rightButton.setEnabled(True)
        self.rightButton.setGeometry(QtCore.QRect(230, 430, 51, 41))
        self.rightButton.setMouseTracking(True)
        self.rightButton.setTabletTracking(True)
        self.rightButton.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.rightButton.setAutoFillBackground(False)
        self.rightButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n")
        self.rightButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("arrow_basic_e.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.rightButton.setIcon(icon)
        original_mouse_press_right = self.rightButton.mousePressEvent
        def custom_mouse_press_right(event):
                self.rightButton.setIcon(QtGui.QIcon("arrow_basic_e_small.png"))
                original_mouse_press_right(event)
        self.rightButton.mousePressEvent = custom_mouse_press_right
        original_mouse_release_right = self.rightButton.mouseReleaseEvent
        def custom_mouse_release_right(event):
                self.rightButton.setIcon(QtGui.QIcon("arrow_basic_e.png"))
                original_mouse_release_right(event)
        self.rightButton.mouseReleaseEvent = custom_mouse_release_right
        self.rightButton.setIconSize(QtCore.QSize(30, 30))
        self.rightButton.setDefault(False)
        self.rightButton.setFlat(True)
        self.rightButton.setObjectName("rightButton")
        self.leftButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.leftButton.setGeometry(QtCore.QRect(70, 430, 61, 41))
        self.leftButton.setMouseTracking(True)
        self.leftButton.setFocusPolicy(QtCore.Qt.FocusPolicy.StrongFocus)
        self.leftButton.setAutoFillBackground(False)
        self.leftButton.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    background-color: transparent;\n"
"}\n")
        self.leftButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("arrow_basic_w.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.leftButton.setIcon(icon1)
        original_mouse_press_left = self.leftButton.mousePressEvent
        def custom_mouse_press_left(event):
                self.leftButton.setIcon(QtGui.QIcon("arrow_basic_w_small.png"))
                original_mouse_press_left(event)
        self.leftButton.mousePressEvent = custom_mouse_press_left
        original_mouse_release_left = self.leftButton.mouseReleaseEvent
        def custom_mouse_release_left(event):
                self.leftButton.setIcon(QtGui.QIcon("arrow_basic_w.png"))
                original_mouse_release_left(event)
        self.leftButton.mouseReleaseEvent = custom_mouse_release_left
        self.leftButton.setIconSize(QtCore.QSize(30, 30))
        self.leftButton.setFlat(True)
        self.leftButton.setObjectName("leftButton")
        self.levelLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.levelLabel.setEnabled(True)
        self.levelLabel.setGeometry(QtCore.QRect(130, 430, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Bradley Hand ITC")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.levelLabel.setFont(font)
        self.levelLabel.setAutoFillBackground(False)
        self.levelLabel.setStyleSheet("color: rgb(25, 76, 152)")
        self.levelLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.levelLabel.setObjectName("levelLabel")
        self.nameLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.nameLabel.setGeometry(QtCore.QRect(0, 0, 501, 71))
        font = QtGui.QFont()
        font.setFamily("Algerian")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nameLabel.setFont(font)
        self.nameLabel.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.nameLabel.setAutoFillBackground(False)
        self.nameLabel.setStyleSheet("color: rgb(25, 76, 152);")
        self.nameLabel.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.nameLabel.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.nameLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.nameLabel.setObjectName("nameLabel")
        self.inforButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.inforButton.setGeometry(QtCore.QRect(360, 430, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.inforButton.setFont(font)
        self.inforButton.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.inforButton.setAutoFillBackground(False)
        self.inforButton.setStyleSheet("color: rgb(25, 76, 152);")
        self.inforButton.setAutoRepeat(False)
        self.inforButton.setFlat(True)
        self.inforButton.setObjectName("inforButton")
        self.inforLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.inforLabel.setEnabled(True)
        self.inforLabel.setGeometry(QtCore.QRect(0, 0, 321, 201))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.inforLabel.setFont(font)
        self.inforLabel.setTabletTracking(True)
        self.inforLabel.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.inforLabel.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.inforLabel.setAcceptDrops(False)
        self.inforLabel.setAutoFillBackground(False)
        self.inforLabel.setStyleSheet("QLabel {\n"
"    background-color: rgb(238, 225, 125);\n"
"    border-radius: 10px;\n"
"}")
        self.inforLabel.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.inforLabel.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.inforLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.inforLabel.setObjectName("inforLabel")
        self.leftButton.raise_()
        self.selectLabel.raise_()
        self.startButton.raise_()
        self.exitButton.raise_()
        self.rightButton.raise_()
        self.levelLabel.raise_()
        self.algoCbBox.raise_()
        self.nameLabel.raise_()
        self.inforButton.raise_()
        self.imageLevelView.raise_()
        self.inforLabel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.algoCbBox.setItemText(0, _translate("MainWindow", "BFS"))
        self.algoCbBox.setItemText(1, _translate("MainWindow", "A*"))
        self.algoCbBox.setItemText(2, _translate("MainWindow", "Beam Search"))
        self.algoCbBox.setItemText(3, _translate("MainWindow", "Backtracking")) 
        self.algoCbBox.setItemText(4, _translate("MainWindow", "And-Or Search"))
        self.algoCbBox.setItemText(5, _translate("MainWindow", "Q-Learning"))
        self.selectLabel.setText(_translate("MainWindow", "Select Algorithm:"))
        self.startButton.setText(_translate("MainWindow", "Start"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.levelLabel.setText(_translate("MainWindow", "Level 1"))
        self.nameLabel.setText(_translate("MainWindow", "Maze Escape"))
        self.inforButton.setText(_translate("MainWindow", "Group 11"))
        self.inforLabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Group 11 Infor</p><p align=\"center\">------------------------------------</p><p align=\"center\">23110245 - Võ Minh Xuân Kiều</p><p align=\"center\">23110297 - Nguyễn Thị Quyến</p><p align=\"center\">23110299 - Trần Thị Như Quỳnh</p></body></html>"))